### PR TITLE
Added autoprefixer via postcss

### PR DESCRIPTION
**Pull request by chris34**
no more mixins for vendor-prefixes \o/

### CODE REVIEW

**Comment by Lyra2108** [comment]
I don't get that is the benefit of this, could you explain it?

**Comment by chris34** [comment]
of course i can :)

I will give an example with border-box (needs a lot of markup for wide browser-support atm). Written in less

```
:fullscreen a {
    display: flex
}
```

could result (after compiling LESS to CSS) in 

```
:-webkit-full-screen a {
    display: -webkit-box;
    display: -webkit-flex;
    display: flex
}
:-moz-full-screen a {
    display: flex
}
:-ms-fullscreen a {
    display: -ms-flexbox;
    display: flex
}
:fullscreen a {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex
}
```

(example just copy&pasted from https://github.com/postcss/autoprefixer-core#quick-example)

The exact output will depend upon the data from caniuse.com and the browsers specified in the settings (the default selector  is `> 1%, last 2 versions, Firefox ESR, Opera 12.1`, see https://github.com/ai/browserslist#browserslist- for more information).

So it will save us from manually adding and managing vendor-prefixes (f.e. via mixins). I used PostCSS for this as the https://github.com/less/less-plugin-autoprefix seems to be some kind of "behind".

**Comment by Lyra2108** [comment]
ok that is useful. You can merge it, if there isn't any thing left from your side. Thank you ^^

**Comment by chris34** [comment]
ok, i will merge it now. thx for the review.

**Pull request merged**
